### ISSUE TITLE
"unexpected fault address" on commit

### ISSUE THREAD

**Issue by calmh** [boltdb/bolt#204]
I see this, intermittently.

go version go1.3 darwin/amd64

Bolt 42b4cae

```
unexpected fault address 0x19441ca
fatal error: fault
[signal 0xb code=0x1 addr=0x19441ca pc=0x45392]

goroutine 33 [running]:
runtime.throw(0x7fb7f3)
        /usr/local/go/src/pkg/runtime/panic.c:520 +0x69 fp=0x1e1eed8 sp=0x1e1eec0
runtime.sigpanic()
        /usr/local/go/src/pkg/runtime/os_darwin.c:457 +0x13f fp=0x1e1eef0 sp=0x1e1eed8
runtime.memmove(0xc2087f224f, 0x19441ca, 0x80)
        /usr/local/go/src/pkg/runtime/memmove_amd64.s:157 +0x192 fp=0x1e1eef8 sp=0x1e1eef0
github.com/boltdb/bolt.(*node).write(0xc20875e230, 0xc2087f2000)
        /Users/jb/src/github.com/boltdb/bolt/node.go:202 +0x361 fp=0x1e1f088 sp=0x1e1eef8
github.com/boltdb/bolt.(*node).spill(0xc208789340, 0x0, 0x0)
        /Users/jb/src/github.com/boltdb/bolt/node.go:335 +0x3f6 fp=0x1e1f240 sp=0x1e1f088
github.com/boltdb/bolt.(*Bucket).spill(0xc20878e480, 0x0, 0x0)
        /Users/jb/src/github.com/boltdb/bolt/bucket.go:543 +0x1c5 fp=0x1e1f438 sp=0x1e1f240
github.com/boltdb/bolt.(*Bucket).spill(0xc20878e330, 0x0, 0x0)
        /Users/jb/src/github.com/boltdb/bolt/bucket.go:514 +0x81e fp=0x1e1f630 sp=0x1e1f438
github.com/boltdb/bolt.(*Bucket).spill(0xc208028aa8, 0x0, 0x0)
        /Users/jb/src/github.com/boltdb/bolt/bucket.go:514 +0x81e fp=0x1e1f828 sp=0x1e1f630
github.com/boltdb/bolt.(*Tx).Commit(0xc208028a90, 0x0, 0x0)
        /Users/jb/src/github.com/boltdb/bolt/tx.go:159 +0x1df fp=0x1e1f960 sp=0x1e1f828
github.com/boltdb/bolt.(*DB).Update(0xc2081b2000, 0xc2084e5fc0, 0x0, 0x0)
        /Users/jb/src/github.com/boltdb/bolt/db.go:468 +0x103 fp=0x1e1f9b8 sp=0x1e1f960
github.com/calmh/syncthing/files.(*Set).Replace(0xc208024d80, 0x1, 0xc20870e000, 0x35a, 0x35a)
        /Users/jb/src/github.com/calmh/syncthing/files/set.go:59 +0x357 fp=0x1e1fb30 sp=0x1e1f9b8
github.com/calmh/syncthing/model.(*Model).Index(0xc2081e0100, 0xc20803c380, 0x34, 0xc208402cd4, 0x3, 0xc208604000, 0x35a, 0x35a)
        /Users/jb/src/github.com/calmh/syncthing/model/model.go:295 +0x82e fp=0x1e1fe00 sp=0x1e1fb30
github.com/calmh/syncthing/protocol.nativeModel.Index(0xa27998, 0xc2081e0100, 0xc20803c380, 0x34, 0xc208402cd4, 0x3, 0xc208604000, 0x35a, 0x35a)
        /Users/jb/src/github.com/calmh/syncthing/protocol/nativemodel_darwin.go:21 +0x13b fp=0x1e1fe70 sp=0x1e1fe00
github.com/calmh/syncthing/protocol.(*nativeModel).Index(0xc2080008c0, 0xc20803c380, 0x34, 0xc208402cd4, 0x3, 0xc208604000, 0x35a, 0x35a)
        <autogenerated>:31 +0xe1 fp=0x1e1fec0 sp=0x1e1fe70
github.com/calmh/syncthing/protocol.(*rawConnection).indexSerializerLoop(0xc2080a0b00)
        /Users/jb/src/github.com/calmh/syncthing/protocol/protocol.go:310 +0x16d fp=0x1e1ffa0 sp=0x1e1fec0
runtime.goexit()
        /usr/local/go/src/pkg/runtime/proc.c:1445 fp=0x1e1ffa8 sp=0x1e1ffa0
created by github.com/calmh/syncthing/protocol.NewConnection
        /Users/jb/src/github.com/calmh/syncthing/protocol/protocol.go:130 +0x58e
```

**Comment by mauleyzaola** [comment]
I am facing this issue, which as far as I understood has to do with the same thing @calmh was having

```
const (
	DEFAULT_DATABASE_FILE_ACCESS = 0600
	DEFAULT_BUCKET_NAME          = "myBucket"
)

type BoltTv struct {
}

func (t *BoltTv) Get(database string, tag string) (data []byte, err error) {
	if len(tag) == 0 {
		return nil, fmt.Errorf("missing tag")
	}
	db, err := t.openDb(database, true)
	if err != nil {
		return nil, err
	}
	defer db.Close()

	err = db.View(func(tx *bolt.Tx) error {
		b := tx.Bucket([]byte(DEFAULT_BUCKET_NAME))
		if b == nil {
			return fmt.Errorf("bucket is nil")
		}
		data = b.Get([]byte(tag))
		return nil
	})
	if err != nil {
		return nil, err
	}

	return data, err
}

func (t *BoltTv) Set(database string, tag string, data []byte) error {
	if len(tag) == 0 {
		return fmt.Errorf("Missing tag")
	}
	if data == nil {
		return fmt.Errorf("missing data")
	}

	db, err := t.openDb(database, false)
	if err != nil {
		return err
	}
	defer db.Close()

	return db.Update(func(tx *bolt.Tx) error {
		b, err := tx.CreateBucketIfNotExists([]byte(DEFAULT_BUCKET_NAME))
		if err != nil {
			return err
		}
		return b.Put([]byte(tag), data)
	})
}

func (t *BoltTv) openDb(database string, readOnly bool) (*bolt.DB, error) {
	if len(database) == 0 {
		return nil, fmt.Errorf("missing database")
	}
	if !strings.HasSuffix(database, ".db") {
		database = database + ".db"
	}
	return bolt.Open(database, DEFAULT_DATABASE_FILE_ACCESS, &bolt.Options{Timeout: 1 * time.Second, ReadOnly: readOnly})
}
```

The error happens on the Get function. This is the initial stack which looks similar from @calmh 's

```
=== RUN TestGetSet
unexpected fault address 0x7ffa8e03b062
fatal error: fault
[signal 0xb code=0x1 addr=0x7ffa8e03b062 pc=0x42b08f]

goroutine 7 [running]:
runtime.gothrow(0x75e7b0, 0x5)
	/usr/local/go/src/runtime/panic.go:503 +0x8e fp=0xc20807dd40 sp=0xc20807dd28
runtime.sigpanic()
```

Funny thing is, before coding that above I did some testing with BoltDb and they have no issues whatsoever. This is the code and you can see the values are being assigned within the transaction as well.

```
func main() {
	db, err := bolt.Open("contacts.db", 0600, nil)
	if err != nil {
		log.Fatal(err)
	}

	defer db.Close()

	newContact := &Contact{}
	newContact.Id = tecutils.UUID() //this is just an unique identifier wrapper, not an issue with that
	newContact.Age = 3
	newContact.Name = "Alaiza"

	err = update(db, newContact)
	if err != nil {
		log.Fatal(err)
	}

	loadedContact, err := load(db, newContact.Id)
	if err != nil {
		log.Fatal(err)
	}
	log.Printf("%#v", newContact)
	log.Printf("%#v", loadedContact)
}

func load(db *bolt.DB, id string) (*Contact, error) {
	data := &Contact{}
	err := db.View(func(tx *bolt.Tx) error {
		b := tx.Bucket([]byte("persons"))
		v := b.Get([]byte(id))
		return json.Unmarshal(v, data)
	})
	return data, err
}

func update(db *bolt.DB, data *Contact) error {
	tx, err := db.Begin(true)
	if err != nil {
		return err
	}

	jsonData, err := json.Marshal(data)
	if err != nil {
		return err
	}
	bucket, err := tx.CreateBucketIfNotExists([]byte("persons"))

	if err != nil {
		tx.Rollback()
		return err
	}
	err = bucket.Put([]byte(data.Id), jsonData)
	if err != nil {
		tx.Rollback()
	} else {
		tx.Commit()
	}
	return err
}

type Contact struct {
	Id    string
	Name  string
	Email string
	Age   int
}
```

My question is: why the first case breaks? I am using Go 1.4.2 on Ubuntu 14.04.3

**Comment by logrusorgru** [comment]
There is code that 100% reproduce this issue for me.

- Go version: `go1.8.3 linux/amd64`
- OS: linux amd64 4.12.7

Just try to write a slice received by `Get`:

```go
package main

import (
	"fmt"
	"os"
	"time"

	"encoding/binary"
	"github.com/boltdb/bolt"
)

const testFileName string = "test.db"

var objs = []byte("o")

func main() {
	defer os.Remove(testFileName)

	b, err := bolt.Open(testFileName, 0644, &bolt.Options{
		Timeout: 500 * time.Millisecond,
	})
	if err != nil {
		fmt.Println(err)
		return
	}
	defer b.Close()

	err = b.Update(func(tx *bolt.Tx) (err error) {
		_, err = tx.CreateBucketIfNotExists(objs)
		return
	})
	if err != nil {
		fmt.Println(err)
		return
	}

	key, val := []byte("one"), []byte{0, 0, 0, 0}

	err = b.Update(func(tx *bolt.Tx) (err error) {
		return tx.Bucket(objs).Put(key, val)
	})
	if err != nil {
		fmt.Println(err)
		return
	}

	err = b.Update(func(tx *bolt.Tx) (err error) {
		bk := tx.Bucket(objs)

		got := bk.Get(key)
		if len(got) == 0 {
			fmt.Println("alredy have")
			return
		}

		binary.LittleEndian.PutUint32(got, 93) // <--- HERE
		return
	})
	if err != nil {
		fmt.Println(err)
		return
	}
}
```

It panics (line with "HERE").

```
unexpected fault address 0x7fb3b1c58054
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x2 addr=0x7fb3b1c58054 pc=0x4a60cb]

goroutine 1 [running]:
runtime.throw(0x4dc6f6, 0x5)
        /opt/go/src/runtime/panic.go:596 +0x95 fp=0xc42003fd58 sp=0xc42003fd38
runtime.sigpanic()
        /opt/go/src/runtime/signal_unix.go:297 +0x28c fp=0xc42003fda8 sp=0xc42003fd58
main.main.func3(0xc42008a1c0, 0x4e3878, 0xc42008a1c0)
        /home/kostyarin/cxo/cxds/bug/bug.go:56 +0x9b fp=0xc42003fe18 sp=0xc42003fda8
github.com/boltdb/bolt.(*DB).Update(0xc420084000, 0xc42003ff20, 0x0, 0x0)
        /home/kostyarin/go/src/github.com/boltdb/bolt/db.go:598 +0x9f fp=0xc42003fe68 sp=0xc42003fe18
main.main()
        /home/kostyarin/cxo/cxds/bug/bug.go:58 +0x3e2 fp=0xc42003ff88 sp=0xc42003fe68
runtime.main()
        /opt/go/src/runtime/proc.go:185 +0x20a fp=0xc42003ffe0 sp=0xc42003ff88
runtime.goexit()
        /opt/go/src/runtime/asm_amd64.s:2197 +0x1 fp=0xc42003ffe8 sp=0xc42003ffe0
exit status 2
```

**Comment by logrusorgru** [comment]
And workaround is:
```go
ng := make([]byte, len(got)
copy(ng, got)
got = ng
```

**Comment by smnchndl** [comment]
Can you please update how to fix this issue. I am also facing same issue in getting key.
