### ISSUE TITLE
panic: index out of range

### ISSUE THREAD

**Issue by tgulacsi** [boltdb/bolt#277]
Hi,

When using BoltDB as an index DB for Camlistore, I got a panic, and an unusable boltdb:
http://www.gthomas.eu/gthomas/camli-index.boltdb.index_out_of_range

```
2015/01/06 12:42:52 http: panic serving 127.0.0.1:48279: runtime error: index out of range
goroutine 681 [running]:
net/http.func·011()
        /usr/local/go/src/net/http/server.go:1130 +0xa8
camlistore.org/third_party/github.com/boltdb/bolt.(*Tx).Commit(0x26a5bb00, 0x0, 0x0)
        /home/gthomas/src/camlistore.org/tmp/build-gopath-nosqlite/src/camlistore.org/third_party/github.com/boltdb/bolt/tx.go:161 +0x2dd
camlistore.org/pkg/sorted/boltdb.(*kvis).CommitBatch(0x191f6c00, 0xb7566518, 0x21aceb30, 0x0, 0x0)
        /home/gthomas/src/camlistore.org/tmp/build-gopath-nosqlite/src/camlistore.org/pkg/sorted/boltdb/boltdb.go:174 +0x122
camlistore.org/pkg/index.(*Index).commit(0x19240f00, 0x21ace9e0, 0x0, 0x0)
        /home/gthomas/src/camlistore.org/tmp/build-gopath-nosqlite/src/camlistore.org/pkg/index/receive.go:272 +0x1ab
camlistore.org/pkg/index.(*Index).ReceiveBlob(0x19240f00, 0xb7563348, 0x21d7f0e0, 0xb75662b0, 0x21d7f100, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/gthomas/src/camlistore.org/tmp/build-gopath-nosqlite/src/camlistore.org/pkg/index/receive.go:239 +0x673
camlistore.org/pkg/serverinit.(*storageAndConfig).ReceiveBlob(0x1923dab0, 0xb7563348, 0x21d7f0e0, 0xb75662b0, 0x21d7f100, 0x0, 0x0, 0x0, 0x0, 0x0)
        <autogenerated>:56 +0x8e
camlistore.org/pkg/blobserver.receive(0xb7566298, 0x1923dab0, 0xb7563348, 0x21d7f0e0, 0xb75662b0, 0x21d7f100, 0x82cc001, 0x0, 0x0, 0x0, ...)
        /home/gthomas/src/camlistore.org/tmp/build-gopath-nosqlite/src/camlistore.org/pkg/blobserver/receive.go:50 +0x216
camlistore.org/pkg/blobserver.Receive(0xb7566298, 0x1923dab0, 0xb7563348, 0x21d7f0e0, 0xb7566280, 0x21ace6e0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/gthomas/src/camlistore.org/tmp/build-gopath-nosqlite/src/camlistore.org/pkg/blobserver/receive.go:38 +0x78
camlistore.org/pkg/blobserver/handlers.handleMultiPartUpload(0xb7565620, 0x1e1ef810, 0x1e1ef260, 0xb7566218, 0x1923dab0)
        /home/gthomas/src/camlistore.org/tmp/build-gopath-nosqlite/src/camlistore.org/pkg/blobserver/handlers/upload.go:230 +0xc97
camlistore.org/pkg/blobserver/handlers.func·007(0xb7565620, 0x1e1ef810, 0x1e1ef260)
        /home/gthomas/src/camlistore.org/tmp/build-gopath-nosqlite/src/camlistore.org/pkg/blobserver/handlers/upload.go:44 +0x42
net/http.HandlerFunc.ServeHTTP(0x1da33fa0, 0xb7565620, 0x1e1ef810, 0x1e1ef260)
        /usr/local/go/src/net/http/server.go:1265 +0x3b
camlistore.org/pkg/auth.func·002(0xb7565620, 0x1e1ef810, 0x1e1ef260)
        /home/gthomas/src/camlistore.org/tmp/build-gopath-nosqlite/src/camlistore.org/pkg/auth/auth.go:379 +0x73
net/http.HandlerFunc.ServeHTTP(0x21ace620, 0xb7565620, 0x1e1ef810, 0x1e1ef260)
        /usr/local/go/src/net/http/server.go:1265 +0x3b
camlistore.org/pkg/serverinit.func·003(0xb7565620, 0x1e1ef810, 0x1e1ef260)
        /home/gthomas/src/camlistore.org/tmp/build-gopath-nosqlite/src/camlistore.org/pkg/serverinit/serverinit.go:188 +0x273
net/http.HandlerFunc.ServeHTTP(0x1923dac0, 0xb7565620, 0x1e1ef810, 0x1e1ef260)
        /usr/local/go/src/net/http/server.go:1265 +0x3b
net/http.(*ServeMux).ServeHTTP(0x1922a800, 0xb7565620, 0x1e1ef810, 0x1e1ef260)
        /usr/local/go/src/net/http/server.go:1541 +0x126
camlistore.org/pkg/webserver.(*Server).ServeHTTP(0x1922c000, 0xb7565620, 0x1e1ef810, 0x1e1ef260)
        /home/gthomas/src/camlistore.org/tmp/build-gopath-nosqlite/src/camlistore.org/pkg/webserver/webserver.go:126 +0x2da
net/http.serverHandler.ServeHTTP(0x193b1140, 0xb7565620, 0x1e1ef810, 0x1e1ef260)
        /usr/local/go/src/net/http/server.go:1703 +0x145
net/http.(*conn).serve(0x1b9e0e40)
        /usr/local/go/src/net/http/server.go:1204 +0x9d8
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:1751 +0x2ce
```

The BoltDB is vendored-in 33e7a074e2c470b6d0b7ee23322a1c4cc759044b. 

How can this happen? What's wrong with my BoltDB usage?
My code can be viewed at https://camlistore-review.googlesource.com/#/c/4299/1/pkg/sorted/boltdb/boltdb.go

**Comment by benbjohnson** [comment]
@tgulacsi I'm just glancing at your code briefly before I head to bed so I haven't had a chance to look very deeply. Are you accessing the `Tx` you create from `DB.Begin()` from multiple goroutines?

**Comment by tgulacsi** [comment]
Maybe. My code is used by a more general code, and I think it is possible
that BeginBatch (which creates the Tx) and CommitBatch (which calls Commit)
is called from different goroutines.

If this may cause such effect, I'll do both in a separate goroutine.

Thanks for your help!
2015. jan. 7. 7:33 ezt írta ("Ben Johnson" <notifications@github.com>):

**Comment by tgulacsi** [comment]
It is reproduced when I call Begin and Commit both in the same goroutine - at the same point of my indexing, with the same data.
Maybe the data is "bad" in some way?

**Comment by tgulacsi** [comment]
This is reproducible.
The code is at https://camlistore-review.googlesource.com/#/c/4299/2/pkg/sorted/boltdb/boltdb.go
The last known good index is at http://git.gthomas.eu/gthomas/camli-index.boltdb.lng
The resulting index is at http://git.gthomas.eu/gthomas/camli-index.boltdb.index_out_of_range
The log file with all the Get/Put/Find is at at http://git.gthomas.eu/gthomas/camli-index.boltdb.log.gz

**Comment by tgulacsi** [comment]
I'll try to write a reproducer; the list of operations is at http://git.gthomas.eu/gthomas/boltlog.json.gz

**Comment by tgulacsi** [comment]
Ok, finally I've managed to reproduce the problem: see https://github.com/tgulacsi/boltcrash

The main culprit is that it is only on i386!
And of course my laptop is 64bit, only my closet file server is 32bit, so the reproduction weren't easy...

**Comment by benbjohnson** [comment]
Thanks for tracking the issue down to i386. I'll have to track down a 386 box to see if I can reproduce the error. How large is the database file? I wonder if it's overflowing the 2GB limit because of int size.

(sorry, I'm writing from my phone so I can't investigate further right now)

**Comment by tgulacsi** [comment]
Nope, just about 256Mb.
2015. jan. 11. 22:45 ezt írta ("Ben Johnson" <notifications@github.com>):

**Comment by tgulacsi** [comment]
Finally, in a Heureka moment, I've figured out that the crash
happens just when the db size exceeds 256Mb - what a nice number!

So a simpler reproduction came: just Put 1Mb values into the db,
and it will panic!

I think that somewhere in BoltDB a numer * 8 (or number << 4)
is stored in an int, and the 32bit limit is reached.

## panic on direct Puts
    go run main.go

```
2015/01/12 07:26:15 i=253
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/boltdb/bolt.(*Tx).page(0x18646180, 0x1005c, 0x0, 0x0)
        /home/gthomas/src/github.com/boltdb/bolt/tx.go:474 +0x9f
github.com/boltdb/bolt.(*Bucket).pageNode(0x18636a80, 0x1005c, 0x0, 0x19a, 0x8057d25)
        /home/gthomas/src/github.com/boltdb/bolt/bucket.go:677 +0x195
github.com/boltdb/bolt.(*Cursor).search(0x197e6a10, 0x1862e6a8, 0x8, 0x8, 0x1005c, 0x0)
        /home/gthomas/src/github.com/boltdb/bolt/cursor.go:230 +0x40
github.com/boltdb/bolt.(*Cursor).searchPage(0x197e6a10, 0x1862e6a8, 0x8, 0x8, 0x98553000)
        /home/gthomas/src/github.com/boltdb/bolt/cursor.go:290 +0x103
github.com/boltdb/bolt.(*Cursor).search(0x197e6a10, 0x1862e6a8, 0x8, 0x8, 0x2, 0x0)
        /home/gthomas/src/github.com/boltdb/bolt/cursor.go:247 +0x303
github.com/boltdb/bolt.(*Cursor).seek(0x197e6a10, 0x1862e6a8, 0x8, 0x8, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/gthomas/src/github.com/boltdb/bolt/cursor.go:144 +0xec
github.com/boltdb/bolt.(*Bucket).Put(0x18636a80, 0x1862e6a8, 0x8, 0x8, 0x1866e000, 0x100000, 0x100000, 0x0, 0x0)
        /home/gthomas/src/github.com/boltdb/bolt/bucket.go:288 +0x21a
main.func·003(0x18646180, 0x0, 0x0)
        /home/gthomas/src/github.com/tgulacsi/boltcrash/main.go:98 +0x102
github.com/boltdb/bolt.(*DB).Update(0x186380e0, 0x197c0e94, 0x0, 0x0)
        /home/gthomas/src/github.com/boltdb/bolt/db.go:459 +0xb8
main.func·004(0xf0, 0x10, 0x0, 0x0)
        /home/gthomas/src/github.com/tgulacsi/boltcrash/main.go:99 +0x168
main.direct(0xbfd247fc, 0x4, 0x0, 0x0)
        /home/gthomas/src/github.com/tgulacsi/boltcrash/main.go:107 +0x395
main.main()
        /home/gthomas/src/github.com/tgulacsi/boltcrash/main.go:47 +0xe5
exit status 2

**Comment by tgulacsi** [comment]
Now I see bolt_386.go contains

    const maxMapSize = 0xFFFFFFF // 256MB

Why can't it be larger? I've tried to enlarge it, but then compilation fails.
I think it could be hacked to have more then one file (map), to sidestep this problem, but that would complicate BoltDB a lot.

The other solution would be forge zero-copy and just mmap the file, and copy data when needed.
