### ISSUE TITLE
Test killed with quit: ran too long.

### ISSUE THREAD

**Issue by omeid** [boltdb/bolt#329]
``` 
 ┌╴testing:go ~/go/src/github.com/boltdb/bolt
 └╴$ (master) go test -v 
seed: 11833
quick settings: count=5, items=1000, ksize=1024, vsize=1024
=== RUN TestFreelist_free
--- PASS: TestFreelist_free (0.00s)
=== RUN TestFreelist_free_overflow
--- PASS: TestFreelist_free_overflow (0.00s)
=== RUN TestFreelist_release
--- PASS: TestFreelist_release (0.00s)
=== RUN TestFreelist_allocate
--- PASS: TestFreelist_allocate (0.00s)
=== RUN TestFreelist_read
--- PASS: TestFreelist_read (0.00s)
=== RUN TestFreelist_write
--- PASS: TestFreelist_write (0.00s)
=== RUN TestNode_put
--- PASS: TestNode_put (0.00s)
=== RUN TestNode_read_LeafPage
--- PASS: TestNode_read_LeafPage (0.00s)
=== RUN TestNode_write_LeafPage
--- PASS: TestNode_write_LeafPage (0.00s)
=== RUN TestNode_split
--- PASS: TestNode_split (0.00s)
=== RUN TestNode_split_MinKeys
--- PASS: TestNode_split_MinKeys (0.00s)
=== RUN TestNode_split_SinglePage
--- PASS: TestNode_split_SinglePage (0.00s)
=== RUN TestPage_typ
--- PASS: TestPage_typ (0.00s)
=== RUN TestPage_dump
00010000000000000000000000000000
--- PASS: TestPage_dump (0.00s)
=== RUN TestBucket_Get_NonExistent
--- PASS: TestBucket_Get_NonExistent (0.06s)
=== RUN TestBucket_Get_FromNode
--- PASS: TestBucket_Get_FromNode (0.01s)
=== RUN TestBucket_Get_IncompatibleValue
--- PASS: TestBucket_Get_IncompatibleValue (0.02s)
=== RUN TestBucket_Put
--- PASS: TestBucket_Put (0.01s)
=== RUN TestBucket_Put_Repeat
--- PASS: TestBucket_Put_Repeat (0.01s)
=== RUN TestBucket_Put_Large
--- PASS: TestBucket_Put_Large (0.62s)
=== RUN TestDB_Put_VeryLarge
--- PASS: TestDB_Put_VeryLarge (16.16s)
=== RUN TestBucket_Put_IncompatibleValue
--- PASS: TestBucket_Put_IncompatibleValue (0.05s)
=== RUN TestBucket_Put_Closed
--- PASS: TestBucket_Put_Closed (0.01s)
=== RUN TestBucket_Put_ReadOnly
--- PASS: TestBucket_Put_ReadOnly (0.02s)
=== RUN TestBucket_Delete
--- PASS: TestBucket_Delete (0.01s)
=== RUN TestBucket_Delete_Large
--- PASS: TestBucket_Delete_Large (0.02s)
=== RUN TestBucket_Delete_FreelistOverflow
  --- PASS: TestBucket_Delete_FreelistOverflow (322.76s)
=== RUN TestBucket_Nested
--- PASS: TestBucket_Nested (0.22s)
=== RUN TestBucket_Delete_Bucket
--- PASS: TestBucket_Delete_Bucket (0.01s)
=== RUN TestBucket_Delete_ReadOnly
--- PASS: TestBucket_Delete_ReadOnly (0.01s)
=== RUN TestBucket_Delete_Closed
--- PASS: TestBucket_Delete_Closed (0.01s)
=== RUN TestBucket_DeleteBucket_Nested
--- PASS: TestBucket_DeleteBucket_Nested (0.02s)
=== RUN TestBucket_DeleteBucket_Nested2
--- PASS: TestBucket_DeleteBucket_Nested2 (0.01s)
=== RUN TestBucket_DeleteBucket_Large
--- PASS: TestBucket_DeleteBucket_Large (0.02s)
=== RUN TestBucket_Bucket_IncompatibleValue
--- PASS: TestBucket_Bucket_IncompatibleValue (0.01s)
=== RUN TestBucket_CreateBucket_IncompatibleValue
--- PASS: TestBucket_CreateBucket_IncompatibleValue (0.01s)
=== RUN TestBucket_DeleteBucket_IncompatibleValue
--- PASS: TestBucket_DeleteBucket_IncompatibleValue (0.01s)
=== RUN TestBucket_NextSequence
--- PASS: TestBucket_NextSequence (0.02s)
=== RUN TestBucket_NextSequence_Persist
--- PASS: TestBucket_NextSequence_Persist (0.02s)
=== RUN TestBucket_NextSequence_ReadOnly
--- PASS: TestBucket_NextSequence_ReadOnly (0.01s)
=== RUN TestBucket_NextSequence_Closed
--- PASS: TestBucket_NextSequence_Closed (0.00s)
=== RUN TestBucket_ForEach
--- PASS: TestBucket_ForEach (0.01s)
=== RUN TestBucket_ForEach_ShortCircuit
--- PASS: TestBucket_ForEach_ShortCircuit (0.01s)
=== RUN TestBucket_ForEach_Closed
--- PASS: TestBucket_ForEach_Closed (0.00s)
=== RUN TestBucket_Put_EmptyKey
--- PASS: TestBucket_Put_EmptyKey (0.01s)
=== RUN TestBucket_Put_KeyTooLarge
--- PASS: TestBucket_Put_KeyTooLarge (0.01s)
=== RUN TestBucket_Stats
--- PASS: TestBucket_Stats (2.97s)
=== RUN TestBucket_Stats_RandomFill
--- PASS: TestBucket_Stats_RandomFill (187.95s)
=== RUN TestBucket_Stats_Small
--- PASS: TestBucket_Stats_Small (0.02s)
=== RUN TestBucket_Stats_EmptyBucket
--- PASS: TestBucket_Stats_EmptyBucket (0.01s)
=== RUN TestBucket_Stats_Nested
--- PASS: TestBucket_Stats_Nested (0.01s)
=== RUN TestBucket_Stats_Large
--- PASS: TestBucket_Stats_Large (5.85s)
=== RUN TestBucket_Put_Single
--- PASS: TestBucket_Put_Single (19.01s)
=== RUN TestBucket_Put_Multiple
--- PASS: TestBucket_Put_Multiple (0.31s)
=== RUN TestBucket_Delete_Quick
--- PASS: TestBucket_Delete_Quick (18.29s)
=== RUN TestCursor_Bucket
--- PASS: TestCursor_Bucket (0.01s)
=== RUN TestCursor_Seek
--- PASS: TestCursor_Seek (0.01s)
=== RUN TestCursor_Delete
--- PASS: TestCursor_Delete (0.03s)
=== RUN TestCursor_Seek_Large
--- PASS: TestCursor_Seek_Large (0.11s)
=== RUN TestCursor_EmptyBucket
--- PASS: TestCursor_EmptyBucket (0.01s)
=== RUN TestCursor_EmptyBucketReverse
--- PASS: TestCursor_EmptyBucketReverse (0.01s)
=== RUN TestCursor_Iterate_Leaf
--- PASS: TestCursor_Iterate_Leaf (0.01s)
=== RUN TestCursor_LeafRootReverse
--- PASS: TestCursor_LeafRootReverse (0.01s)
=== RUN TestCursor_Restart
--- PASS: TestCursor_Restart (0.01s)
=== RUN TestCursor_QuickCheck
--- PASS: TestCursor_QuickCheck (0.82s)
=== RUN TestCursor_QuickCheck_Reverse
--- PASS: TestCursor_QuickCheck_Reverse (1.05s)
=== RUN TestCursor_QuickCheck_BucketsOnly
--- PASS: TestCursor_QuickCheck_BucketsOnly (0.01s)
=== RUN TestCursor_QuickCheck_BucketsOnly_Reverse
--- PASS: TestCursor_QuickCheck_BucketsOnly_Reverse (0.01s)
=== RUN TestOpen_BadPath
--- PASS: TestOpen_BadPath (0.00s)
=== RUN TestOpen
--- PASS: TestOpen (0.01s)
=== RUN TestOpen_Timeout
--- PASS: TestOpen_Timeout (0.11s)
=== RUN TestOpen_Wait
--- PASS: TestOpen_Wait (0.11s)
=== RUN TestOpen_Size
--- PASS: TestOpen_Size (0.66s)
=== RUN TestOpen_Size_Large
SIGQUIT: quit
PC=0x428b36

goroutine 0 [idle]:
markroot(0xc208010000, 0xc200000003)
	/usr/local/go/src/runtime/mgc0.c:512 +0x256 fp=0x7fffe2fee3a0 sp=0x7fffe2fee340
runtime.parfordo(0xc208010000)
	/usr/local/go/src/runtime/parfor.c:76 +0xb2 fp=0x7fffe2fee420 sp=0x7fffe2fee3a0
gc(0x7fffe2fee558)
	/usr/local/go/src/runtime/mgc0.c:1439 +0x25e fp=0x7fffe2fee538 sp=0x7fffe2fee420
runtime.gc_m()
	/usr/local/go/src/runtime/mgc0.c:1368 +0xe0 fp=0x7fffe2fee570 sp=0x7fffe2fee538
runtime.onM(0x6be070)
	/usr/local/go/src/runtime/asm_amd64.s:257 +0x68 fp=0x7fffe2fee578 sp=0x7fffe2fee570
runtime.mstart()
	/usr/local/go/src/runtime/proc.c:818 fp=0x7fffe2fee580 sp=0x7fffe2fee578

goroutine 164 [garbage collection]:
runtime.switchtoM()
	/usr/local/go/src/runtime/asm_amd64.s:198 fp=0xc20805c900 sp=0xc20805c8f8
runtime.gogc(0x0)
	/usr/local/go/src/runtime/malloc.go:469 +0x1cf fp=0xc20805c938 sp=0xc20805c900
runtime.mallocgc(0x1c000, 0x5aa180, 0xc200000000, 0x8)
	/usr/local/go/src/runtime/malloc.go:341 +0x391 fp=0xc20805c9e8 sp=0xc20805c938
runtime.newarray(0x5aa180, 0x700, 0xc24b858000)
	/usr/local/go/src/runtime/malloc.go:365 +0xc1 fp=0xc20805ca20 sp=0xc20805c9e8
runtime.growslice(0x55c400, 0xc24b858000, 0x380, 0x380, 0x1, 0x0, 0x0, 0x0)
	/usr/local/go/src/runtime/slice.go:87 +0x2bb fp=0xc20805ca80 sp=0xc20805ca20
github.com/boltdb/bolt.(*node).put(0xc24b8792d0, 0xc24b3e59e0, 0x8, 0x8, 0xc24b3e59e0, 0x8, 0x8, 0xc24b64f980, 0x32, 0x32, ...)
	/home/go/go/src/github.com/boltdb/bolt/node.go:131 +0x470 fp=0xc20805cbc0 sp=0xc20805ca80
github.com/boltdb/bolt.(*Bucket).Put(0xc24b636280, 0xc24b3e59e0, 0x8, 0x8, 0xc24b64f980, 0x32, 0x32, 0x0, 0x0)
	/home/go/go/src/github.com/boltdb/bolt/bucket.go:297 +0x4ce fp=0xc20805ccf0 sp=0xc20805cbc0
github.com/boltdb/bolt_test.func·108(0xc20801e1a0, 0x0, 0x0)
	/home/go/go/src/github.com/boltdb/bolt/db_test.go:147 +0x179 fp=0xc20805cdb8 sp=0xc20805ccf0
github.com/boltdb/bolt.(*DB).Update(0xc24b650180, 0xc20805cf38, 0x0, 0x0)
	/home/go/go/src/github.com/boltdb/bolt/db.go:476 +0xde fp=0xc20805ce20 sp=0xc20805cdb8
github.com/boltdb/bolt_test.TestOpen_Size_Large(0xc24b820510)
	/home/go/go/src/github.com/boltdb/bolt/db_test.go:151 +0x202 fp=0xc20805cf78 sp=0xc20805ce20
testing.tRunner(0xc24b820510, 0x6bcf78)
	/usr/local/go/src/testing/testing.go:447 +0xbf fp=0xc20805cfd0 sp=0xc20805cf78
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc20805cfd8 sp=0xc20805cfd0
created by testing.RunTests
	/usr/local/go/src/testing/testing.go:555 +0xa8b

goroutine 1 [chan receive]:
runtime.gopark(0x433620, 0xc208036298, 0x5dda70, 0xc)
	/usr/local/go/src/runtime/proc.go:130 +0x105 fp=0xc20805dba8 sp=0xc20805db78
runtime.goparkunlock(0xc208036298, 0x5dda70, 0xc)
	/usr/local/go/src/runtime/proc.go:136 +0x48 fp=0xc20805dbd0 sp=0xc20805dba8
runtime.chanrecv(0x554400, 0xc208036240, 0xc20805ddc0, 0x458201, 0x0)
	/usr/local/go/src/runtime/chan.go:410 +0x452 fp=0xc20805dc70 sp=0xc20805dbd0
runtime.chanrecv1(0x554400, 0xc208036240, 0xc20805ddc0)
	/usr/local/go/src/runtime/chan.go:311 +0x2b fp=0xc20805dca0 sp=0xc20805dc70
testing.RunTests(0x6235a0, 0x6bc8a0, 0x80, 0x80, 0x6be401)
	/usr/local/go/src/testing/testing.go:556 +0xad6 fp=0xc20805de48 sp=0xc20805dca0
testing.(*M).Run(0xc2080340a0, 0x6bb840)
	/usr/local/go/src/testing/testing.go:485 +0x6c fp=0xc20805ded0 sp=0xc20805de48
main.main()
	github.com/boltdb/bolt/_test/_testmain.go:328 +0x1d5 fp=0xc20805df98 sp=0xc20805ded0
runtime.main()
	/usr/local/go/src/runtime/proc.go:63 +0xf3 fp=0xc20805dfe0 sp=0xc20805df98
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc20805dfe8 sp=0xc20805dfe0

goroutine 2 [force gc (idle), 9 minutes]:
runtime.gopark(0x433620, 0x6bdbf0, 0x5debd0, 0xf)
	/usr/local/go/src/runtime/proc.go:130 +0x105 fp=0xc20801a798 sp=0xc20801a768
runtime.goparkunlock(0x6bdbf0, 0x5debd0, 0xf)
	/usr/local/go/src/runtime/proc.go:136 +0x48 fp=0xc20801a7c0 sp=0xc20801a798
runtime.forcegchelper()
	/usr/local/go/src/runtime/proc.go:99 +0xce fp=0xc20801a7e0 sp=0xc20801a7c0
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc20801a7e8 sp=0xc20801a7e0
created by runtime.init·4
	/usr/local/go/src/runtime/proc.go:87 +0x25

goroutine 3 [runnable]:
runtime.Gosched()
	/usr/local/go/src/runtime/proc.go:113 +0x14 fp=0xc20801dfc0 sp=0xc20801dfb0
runtime.bgsweep()
	/usr/local/go/src/runtime/mgc0.go:87 +0x59 fp=0xc20801dfe0 sp=0xc20801dfc0
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc20801dfe8 sp=0xc20801dfe0
created by gc
	/usr/local/go/src/runtime/mgc0.c:1383

goroutine 4 [finalizer wait]:
runtime.gopark(0x433620, 0x6c50c0, 0x5de590, 0xe)
	/usr/local/go/src/runtime/proc.go:130 +0x105 fp=0xc208018f30 sp=0xc208018f00
runtime.goparkunlock(0x6c50c0, 0x5de590, 0xe)
	/usr/local/go/src/runtime/proc.go:136 +0x48 fp=0xc208018f58 sp=0xc208018f30
runtime.runfinq()
	/usr/local/go/src/runtime/malloc.go:727 +0xba fp=0xc208018fe0 sp=0xc208018f58
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc208018fe8 sp=0xc208018fe0
created by runtime.createfing
	/usr/local/go/src/runtime/malloc.go:707 +0x5e

goroutine 160 [timer goroutine (idle)]:
runtime.gopark(0x433620, 0x6bdde0, 0x5f4ff0, 0x16)
	/usr/local/go/src/runtime/proc.go:130 +0x105 fp=0xc208019f40 sp=0xc208019f10
runtime.goparkunlock(0x6bdde0, 0x5f4ff0, 0x16)
	/usr/local/go/src/runtime/proc.go:136 +0x48 fp=0xc208019f68 sp=0xc208019f40
runtime.timerproc()
	/usr/local/go/src/runtime/time.go:200 +0x130 fp=0xc208019fe0 sp=0xc208019f68
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc208019fe8 sp=0xc208019fe0
created by runtime.addtimerLocked
	/usr/local/go/src/runtime/time.go:113 +0x1ba

rax     0x4
rbx     0xaa08
rcx     0x7f3278a4a000
rdx     0xaa08
rdi     0x0
rsi     0xc208032660
rbp     0x7f3279127fd8
rsp     0x7fffe2fee340
r8      0x0
r9      0xc208000000
r10     0xc207ffcd99
r11     0x8
r12     0x7f32798bb800
r13     0x1
r14     0x270f
r15     0x10
rip     0x428b36
rflags  0x283
cs      0x33
fs      0x0
gs      0x0
*** Test killed with quit: ran too long (10m0s).
FAIL	github.com/boltdb/bolt	600.078s
```

System Specs (Virtual Machine):

```
$ lscpu
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                4
On-line CPU(s) list:   0-3
Thread(s) per core:    1
Core(s) per socket:    4
Socket(s):             1
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 42
Model name:            Intel(R) Core(TM) i7-2670QM CPU @ 2.20GHz
Stepping:              7
CPU MHz:               2196.265
BogoMIPS:              4392.53
L1d cache:             32K
L1d cache:             32K
L2d cache:             6144K
NUMA node0 CPU(s):     0-3

$ uname  -srv
Linux 3.10.0-123.20.1.el7.x86_64
```

**Comment by benbjohnson** [comment]
Are you running on an SSD or spinning disk?

**Comment by omeid** [comment]
Spinning, and the vm disk is a vdi if that makes a difference.

**Comment by benbjohnson** [comment]
The CI test suite runs in 9½ minutes on Drone and that's with SSDs so you'll probably need to bump up your `-timeout` flag if you're running on spinning disk. Bolt can be a lot slower on spinning disk.

The test runtime is so long because there's a lot of simulation testing going on and `testing/quick` tests that generate random data against the database.

https://drone.io/github.com/boltdb/bolt/244
