### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by oknoorap** [boltdb/bolt#358]
I'm using ubuntu, I got error while running it:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x8 pc=0x400ea8]

goroutine 16 [running]:
runtime.panic(0x4eb9e0, 0x5a4953)
        /usr/lib/go/src/pkg/runtime/panic.c:279 +0xf5
main.func·001(0xc208028000, 0x0, 0x0)
        /home/web/test.go:31 +0x88
github.com/boltdb/bolt.(*DB).View(0xc20802c820, 0x539ff8, 0x0, 0x0)
        /home/src/github.com/boltdb/bolt/db.go:536 +0xe4
main.main()
        /home/web/test.go:40 +0x152

goroutine 19 [finalizer wait]:
runtime.park(0x413490, 0x5a8970, 0x5a7489)
        /usr/lib/go/src/pkg/runtime/proc.c:1369 +0x89
runtime.parkunlock(0x5a8970, 0x5a7489)
        /usr/lib/go/src/pkg/runtime/proc.c:1385 +0x3b
runfinq()
        /usr/lib/go/src/pkg/runtime/mgc0.c:2644 +0xcf
runtime.goexit()
        /usr/lib/go/src/pkg/runtime/proc.c:1445
```

my code:
```
package main

import (
"fmt"
"bytes"
"log"
"github.com/boltdb/bolt"
)

func main() {
	db, err := bolt.Open("engine.db", 0600, nil)
	if err != nil {
		log.Print("error")
	}
	defer db.Close()

	view := db.View(func(tx *bolt.Tx) error {
		c := tx.Bucket([]byte("posts")).Cursor()

		prefix := []byte("/test")
		for k, v := c.Seek(prefix); bytes.HasPrefix(k, prefix); k, v = c.Next() {
			fmt.Printf("key=%s, value=%s\n", k, v)
		}

		return nil
	})

	fmt.Print(view)
}
```

**Comment by benbjohnson** [comment]
Is the "posts" bucket non-nil?

**Comment by oknoorap** [comment]
sorry it's my bad

**Comment by benbjohnson** [comment]
No problem! Let me know if you have any other questions.
