### ISSUE TITLE
go test crashes on Put_VeryLarge with file resize error

### ISSUE THREAD

**Issue by djherbis** [boltdb/bolt#517]
I'm consistently getting the following crash during go test.

```
go version
go version go1.6 windows/amd64

go test
seed: 90300
quick settings: count=5, items=1000, ksize=1024, vsize=1024
00010000000000000000000000000000
--- FAIL: TestDB_Put_VeryLarge (2.08s)
        bucket_test.go:194: file resize error: truncate C:\Users\DJHER_~1\AppData\Local\Temp\bolt-309957413: The requested operation cannot be performed on a file with a user-mapped section open.
panic: file resize error: truncate C:\Users\DJHER_~1\AppData\Local\Temp\bolt-309957413: The requested operation cannot be performed on a file with a user-mapped section open. [recovered]
        panic: file resize error: truncate C:\Users\DJHER_~1\AppData\Local\Temp\bolt-309957413: The requested operation cannot be performed on a file with a user-mapped section open.

goroutine 51 [running]:
panic(0x60a960, 0xc0a5cdbdf0)
        C:/Go/src/runtime/panic.go:464 +0x3f4
testing.tRunner.func1(0xc0821138c0)
        C:/Go/src/testing/testing.go:467 +0x199
panic(0x60a960, 0xc0a5cdbdf0)
        C:/Go/src/runtime/panic.go:426 +0x4f7
github.com/boltdb/bolt_test.(*DB).MustCheck(0xc082026040)
        D:/Dropbox/Go/src/github.com/boltdb/bolt/db_test.go:1590 +0xd2
github.com/boltdb/bolt_test.(*DB).Close(0xc082026040, 0x0, 0x0)
        D:/Dropbox/Go/src/github.com/boltdb/bolt/db_test.go:1527 +0x55
github.com/boltdb/bolt_test.(*DB).MustClose(0xc082026040)
        D:/Dropbox/Go/src/github.com/boltdb/bolt/db_test.go:1536 +0x28
runtime.Goexit()
        C:/Go/src/runtime/panic.go:323 +0x109
testing.(*common).FailNow(0xc0821138c0)
        C:/Go/src/testing/testing.go:346 +0x3d
testing.(*common).Fatal(0xc0821138c0, 0xc089ddbeb8, 0x1, 0x1)
        C:/Go/src/testing/testing.go:383 +0x76
github.com/boltdb/bolt_test.TestDB_Put_VeryLarge(0xc0821138c0)
        D:/Dropbox/Go/src/github.com/boltdb/bolt/bucket_test.go:194 +0x2ee
testing.tRunner(0xc0821138c0, 0x763e10)
        C:/Go/src/testing/testing.go:473 +0x9f
created by testing.RunTests
        C:/Go/src/testing/testing.go:582 +0x899
exit status 2
FAIL    github.com/boltdb/bolt  3.209s
```

**Comment by benbjohnson** [comment]
I just bought a Windows laptop to dive into some of the Bolt Windows issues (and to set up as a CI server). Thanks for submitting the issue. I should have a fix soon.

**Comment by davecgh** [comment]
I was looking to sync to the latest code and am seeing this too.

**Comment by ChrisHines** [comment]
I had reproduced this problem before, but now this test passes for me on my go 1.6 windows/amd64 box.

Consider closing this issue.

**Comment by benbjohnson** [comment]
@ChrisHines Thanks for investigating. I did some Windows clean up recently but I missed closing some of the related issues.

**Comment by djherbis** [comment]
I can confirm this test passes for me too now.
