### ISSUE TITLE
Hangs on Debian/Linux but not on OS X

### ISSUE THREAD

**Issue by andreiamatuni** [boltdb/bolt#566]
example code:
```go
package main

import (
	"fmt"
	"log"

	"github.com/boltdb/bolt"
)

func main() {
	db, err := bolt.Open("my.db", 0600, nil)

	if err != nil {
		log.Fatal(err)
	}
	defer db.Close()

	db.Update(func(tx *bolt.Tx) error {
		b, err := tx.CreateBucket([]byte("MyBucket"))
		if err != nil {
			return fmt.Errorf("create bucket: %s", err)
		}
		b.Put([]byte("answer"), []byte("42"))
		return nil
	})

}
```

The my.db file will be created, but the process will then hang without doing anything else (and the my.db file is empty). This code runs fine on OS X, but not on Debian Linux. What should I do?

**Comment by benbjohnson** [comment]
Can you provide a stack trace (send a `SIGQUIT` signal or hit `CTRL-\`)?

**Comment by andreiamatuni** [comment]
```ctrl-\``` and ```kill -3 PID``` aren't working. only way I can stop the process is ```kill -9 PID```

**Comment by andreiamatuni** [comment]
just passed it ```kill -2 PID``` and got this backtrace:

```
goroutine 0 [idle]:
runtime.rtsigprocmask(0xc800000002, 0xc820033894, 0x0)
	/hlpUsers/aamatuni/go/src/runtime/sys_linux_amd64.s:206 +0x1a
runtime.updatesigmask(0x0, 0x0)
	/hlpUsers/aamatuni/go/src/runtime/os1_linux.go:381 +0xfd
runtime.dieFromSignal(0x2)
	/hlpUsers/aamatuni/go/src/runtime/signal1_unix.go:191 +0x3c
runtime.sighandler(0xc800000002, 0xc820033bb0, 0xc820033a80, 0xc820000480)
	/hlpUsers/aamatuni/go/src/runtime/signal_amd64x.go:147 +0x308
runtime.sigtrampgo(0x2, 0xc820033bb0, 0xc820033a80)
	/hlpUsers/aamatuni/go/src/runtime/signal_sigtramp.go:48 +0xf6
runtime.sigtramp(0x1, 0x0, 0xc82002c000, 0x0, 0x7fa0, 0x0, 0x0, 0xc820039eb0, 0x246, 0x42d730, ...)
	/hlpUsers/aamatuni/go/src/runtime/sys_linux_amd64.s:234 +0x1b
runtime.sigreturn(0x0, 0xc82002c000, 0x0, 0x7fa0, 0x0, 0x0, 0xc820039eb0, 0x246, 0x42d730, 0x56ef60, ...)
	/hlpUsers/aamatuni/go/src/runtime/sys_linux_amd64.s:238

goroutine 1 [syscall]:
syscall.Syscall(0x49, 0x3, 0x6, 0x0, 0x4bb1f8, 0x57585370, 0xc834c20e54)
	/hlpUsers/aamatuni/go/src/syscall/asm_linux_amd64.s:18 +0x5
syscall.Flock(0x3, 0x6, 0x0, 0x0)
	/hlpUsers/aamatuni/go/src/syscall/zsyscall_linux_amd64.go:482 +0x4b
github.com/boltdb/bolt.flock(0xc820084000, 0x100000180, 0x0, 0x0, 0x0)
	/hlpUsers/aamatuni/gocode/src/github.com/boltdb/bolt/bolt_unix.go:30 +0xcc
github.com/boltdb/bolt.Open(0x538190, 0x5, 0x180, 0x5ff5c0, 0xc820068058, 0x0, 0x0)
	/hlpUsers/aamatuni/gocode/src/github.com/boltdb/bolt/db.go:186 +0x23a
main.main()
	/hlpUsers/aamatuni/code/test/main.go:11 +0x51

rax    0x0
rbx    0xc820033894
rcx    0x457d7a
rdx    0x0
rdi    0x2
rsi    0xc820033894
rbp    0x3
rsp    0xc820033868
r8     0x0
r9     0xc820000300
r10    0x8
r11    0x246
r12    0x42d730
r13    0x56ef60
r14    0x0
r15    0x8
rip    0x457d7a
rflags 0x246
cs     0x33
fs     0x0
gs     0x0
```

**Comment by benbjohnson** [comment]
It looks like `my.db` is being locked by another process. You can try `lsof` or `lslk` to find which process is locking it:

http://unix.stackexchange.com/questions/85994/how-to-list-processes-locking-file

**Comment by andreiamatuni** [comment]
when I run ```lsof | grep "my.db"``` the only processes that show up are 5 instances of the main.go process:

```
test      30461             aamatuni    3u      REG               0,40        0   48969890 /mnt/hlpUsers/aamatuni/code/test/my.db (123.45.678.90:/volume1/homes)
test      30461 30462       aamatuni    3u      REG               0,40        0   48969890 /mnt/hlpUsers/aamatuni/code/test/my.db (123.45.678.90:/volume1/homes)
test      30461 30463       aamatuni    3u      REG               0,40        0   48969890 /mnt/hlpUsers/aamatuni/code/test/my.db (123.45.678.90:/volume1/homes)
test      30461 30464       aamatuni    3u      REG               0,40        0   48969890 /mnt/hlpUsers/aamatuni/code/test/my.db (123.45.678.90:/volume1/homes)
test      30461 30465       aamatuni    3u      REG               0,40        0   48969890 /mnt/hlpUsers/aamatuni/code/test/my.db (123.45.678.90:/volume1/homes)
```

**Comment by benbjohnson** [comment]
Can you kill all those processes and try again? Only one process can access a bolt database at a time. Perhaps the first process is hanging on something different besides `flock()`.

**Comment by andreiamatuni** [comment]
It's a single process. I think it shows up 5 times because of the different threads the goroutines are scheduled on (PID is all the same [30461], TID is different [30462-5]). I killed the process and all 5 entries went away. I started it up again and it hangs again (with 5 entries showing up in ```lsof```)

**Comment by benbjohnson** [comment]
Hmm. I'm not sure why it would be a problem. I've deployed on Linux many times. How is your `/mnt/hlpUsers` directory mounted? Does this program work in other directories (like your home directory)?

**Comment by andreiamatuni** [comment]
I think the problem is that my home folder is mounted as a NFS. I'm going to try and change the path of the .db files to the server's native filesystem tomorrow and see if this fixes things.

**Comment by andreiamatuni** [comment]
yep, that fixed the problem
