### ISSUE TITLE
panic: page 178 already freed

### ISSUE THREAD

**Issue by GameXG** [boltdb/bolt#648]
The g-drive is a mapped NFS @ FreeNAS network drive. In the g-disk test will be panic . Able to reproduce. Panic does not appear on the local disk test. 

General not in the network drive above the use of boltdb, but I do not know is not in other cases will panic, but the local disk probability is small?

Related:#348 

```
"C:\Program Files (x86)\JetBrains\Gogland 163.10615.6\bin\runnerw.exe" C:/Go\bin\go.exe run G:/编程/golang/src/github.com/gamexg/go-test/数据库/boltdb/1.go
panic: page 178 already freed

goroutine 8846 [running]:
panic(0x4c8980, 0xc04235b890)
	C:/Go/src/runtime/panic.go:500 +0x1af
github.com/boltdb/bolt.(*freelist).free(0xc04203ff50, 0x2254, 0x2522000)
	G:/编程/golang/src/github.com/boltdb/bolt/freelist.go:117 +0x2c7
github.com/boltdb/bolt.(*node).spill(0xc04230a620, 0xc042462280, 0xc042462280)
	G:/编程/golang/src/github.com/boltdb/bolt/node.go:358 +0x1e3
github.com/boltdb/bolt.(*node).spill(0xc04230a5b0, 0xc0424d6630, 0xc0421119e0)
	G:/编程/golang/src/github.com/boltdb/bolt/node.go:345 +0xbe
github.com/boltdb/bolt.(*Bucket).spill(0xc0423bae80, 0xc0424d6500, 0xc042111c50)
	G:/编程/golang/src/github.com/boltdb/bolt/bucket.go:541 +0x442
github.com/boltdb/bolt.(*Bucket).spill(0xc04206d898, 0x219cf650, 0x566800)
	G:/编程/golang/src/github.com/boltdb/bolt/bucket.go:508 +0x942
github.com/boltdb/bolt.(*Tx).Commit(0xc04206d880, 0x0, 0x0)
	G:/编程/golang/src/github.com/boltdb/bolt/tx.go:163 +0x12c
github.com/boltdb/bolt.(*DB).Update(0xc042078000, 0xc04225bed0, 0x0, 0x0)
	G:/编程/golang/src/github.com/boltdb/bolt/db.go:602 +0x114
github.com/boltdb/bolt.(*batch).run(0xc042249300)
	G:/编程/golang/src/github.com/boltdb/bolt/db.go:722 +0x106
github.com/boltdb/bolt.(*batch).(github.com/boltdb/bolt.run)-fm()
	G:/编程/golang/src/github.com/boltdb/bolt/db.go:696 +0x31
sync.(*Once).Do(0xc042249310, 0xc04225bf58)
	C:/Go/src/sync/once.go:44 +0xe2
github.com/boltdb/bolt.(*batch).trigger(0xc042249300)
	G:/编程/golang/src/github.com/boltdb/bolt/db.go:696 +0x53
github.com/boltdb/bolt.(*batch).(github.com/boltdb/bolt.trigger)-fm()
	G:/编程/golang/src/github.com/boltdb/bolt/db.go:666 +0x31
created by time.goFunc
	C:/Go/src/time/sleep.go:154 +0x4b
exit status 2
```

 windows 7 in esxi@nfs

``` go
package main

import (
	"log"

	"fmt"
	"time"

	"os"

	"github.com/boltdb/bolt"
)

func test1() {
	// Open the my.db data file in your current directory.
	// It will be created if it doesn't exist.
	os.Remove("test1.db")
	db, err := bolt.Open("test1.db", 0600, nil)
	if err != nil {
		log.Fatal(err)
	}
	defer db.Close()

	err = db.Update(func(tx *bolt.Tx) error {
		_, err := tx.CreateBucketIfNotExists([]byte("MyBucket"))
		return err
	})
	if err != nil {

	}

	sTime := time.Now()
	for i := 0; i < 10000; i++ {
		err = db.Update(func(tx *bolt.Tx) error {
			b := tx.Bucket([]byte("MyBucket"))
			err := b.Put([]byte(fmt.Sprint("key", i)), []byte("00000000000000000000"))
			return err
		})
	}
	//每次创建 Bucket 耗时： 33.2749032s
	fmt.Println("每次创建 Bucket 耗时：", time.Now().Sub(sTime))
}

func test2() {
	// Open the my.db data file in your current directory.
	// It will be created if it doesn't exist.
	os.Remove("test2.db")
	db, err := bolt.Open("test2.db", 0600, nil)
	if err != nil {
		log.Fatal(err)
	}
	defer db.Close()

	err = db.Update(func(tx *bolt.Tx) error {
		_, err := tx.CreateBucketIfNotExists([]byte("MyBucket"))
		return err
	})
	if err != nil {

	}

	sTime := time.Now()
	for i := 0; i < 10000; i++ {
		err = db.Batch(func(tx *bolt.Tx) error {
			b := tx.Bucket([]byte("MyBucket"))
			err := b.Put([]byte(fmt.Sprint("key", i)), []byte("00000000000000000000"))
			return err
		})
	}

	fmt.Println("批量操作：", time.Now().Sub(sTime))
}
func test3() {
	// Open the my.db data file in your current directory.
	// It will be created if it doesn't exist.
	os.Remove("test3.db")
	db, err := bolt.Open("test3.db", 0600, nil)
	if err != nil {
		log.Fatal(err)
	}
	defer db.Close()

	err = db.Update(func(tx *bolt.Tx) error {
		_, err := tx.CreateBucketIfNotExists([]byte("MyBucket"))
		return err
	})
	if err != nil {

	}

	sTime := time.Now()
	err = db.Update(func(tx *bolt.Tx) error {
		b := tx.Bucket([]byte("MyBucket"))
		for i := 0; i < 10000; i++ {
			err := b.Put([]byte(fmt.Sprint("key", i)), []byte("00000000000000000000"))
			if err != nil {
				return err
			}
		}
		return nil
	})
	//单次事务执行： 100.0057ms
	fmt.Println("单次事务执行：", time.Now().Sub(sTime))
}

func main() {
	//test1()
	test2()
}

```

**Comment by GameXG** [comment]
Update to the new version tried several times not in reproduction.
