### ISSUE TITLE
SIGSEV under heavy read and write load

### ISSUE THREAD

**Issue by vrecan** [boltdb/bolt#658]
Under heavy load I can consistently cause this issue. I have run with gorace as well and it doesn't detect any sharing violations.
```
unexpected fault address 0x7f78c01f63e2
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x1 addr=0x7f78c01f63e2 pc=0x4653c9]

goroutine 2082770 [running]:
runtime.throw(0xde9151, 0x5)
	/usr/local/go/src/runtime/panic.go:566 +0x95 fp=0xc4220ea820 sp=0xc4220ea800
runtime.sigpanic()
	/usr/local/go/src/runtime/sigpanic_unix.go:27 +0x288 fp=0xc4220ea878 sp=0xc4220ea820
runtime.cmpbody()
	/usr/local/go/src/runtime/asm_amd64.s:1552 +0xf9 fp=0xc4220ea880 sp=0xc4220ea878
github.schq.secious.com/UltraViolet/Winston/vendor/github.com/boltdb/bolt.(*Cursor).searchPage.func1(0xa, 0x0)
	/home/vrecan/go/src/github.schq.secious.com/UltraViolet/Winston/vendor/github.com/boltdb/bolt/cursor.go:302 +0x175 fp=0xc4220ea920 sp=0xc4220ea880
sort.Search(0x14, 0xc4220ea9c8, 0xc4220eaa08)
	/usr/local/go/src/sort/search.go:66 +0x74 fp=0xc4220ea960 sp=0xc4220ea920
github.schq.secious.com/UltraViolet/Winston/vendor/github.com/boltdb/bolt.(*Cursor).searchPage(0xc4220eb1e0, 0x7f78c01f63e2, 0xc, 0xc, 0x7f7828007000)
	/home/vrecan/go/src/github.schq.secious.com/UltraViolet/Winston/vendor/github.com/boltdb/bolt/cursor.go:307 +0x155 fp=0xc4220eaa18 sp=0xc4220ea960
github.schq.secious.com/UltraViolet/Winston/vendor/github.com/boltdb/bolt.(*Cursor).search(0xc4220eb1e0, 0x7f78c01f63e2, 0xc, 0xc, 0x7)
	/home/vrecan/go/src/github.schq.secious.com/UltraViolet/Winston/vendor/github.com/boltdb/bolt/cursor.go:271 +0x2c7 fp=0xc4220eab00 sp=0xc4220eaa18
github.schq.secious.com/UltraViolet/Winston/vendor/github.com/boltdb/bolt.(*Cursor).seek(0xc4220eb1e0, 0x7f78c01f63e2, 0xc, 0xc, 0xc423ca7680, 0x40, 0xc4220eac80, 0x412d38, 0xc4204ba800, 0x40, ...)
	/home/vrecan/go/src/github.schq.secious.com/UltraViolet/Winston/vendor/github.com/boltdb/bolt/cursor.go:159 +0x19a fp=0xc4220eaba8 sp=0xc4220eab00
github.schq.secious.com/UltraViolet/Winston/vendor/github.com/boltdb/bolt.(*Cursor).Seek(0xc4220eb1e0, 0x7f78c01f63e2, 0xc, 0xc, 0x0, 0x0, 0x1, 0xc423ca7680, 0xc4220eade8, 0x90740e)
	/home/vrecan/go/src/github.schq.secious.com/UltraViolet/Winston/vendor/github.com/boltdb/bolt/cursor.go:118 +0x78 fp=0xc4220eac70 sp=0xc4220eaba8
github.schq.secious.com/UltraViolet/Winston/lfdb/index.ReadTimeIndexCursor(0x7f78c01f63e2, 0xc, 0xc, 0x2f9b9, 0x1388, 0x1496a3a07fd64200, 0x149fd90987184200, 0xc4220eb1e0, 0x0, 0x0, ...)
	/home/vrecan/go/src/github.schq.secious.com/UltraViolet/Winston/lfdb/index/batchdb.go:212 +0xc4 fp=0xc4220eae28 sp=0xc4220eac70
github.schq.secious.com/UltraViolet/Winston/lfdb/index.ReadNKeysFromTimeIndex(0x7f78c01f63e2, 0xc, 0xc, 0x2f9b9, 0x1388, 0x1496a3a07fd64200, 0x149fd90987184200, 0xc4220eb1e0, 0xa218cd57a7e2df93, 0xc4239e08d8, ...)
	/home/vrecan/go/src/github.schq.secious.com/UltraViolet/Winston/lfdb/index/batchdb.go:276 +0x2d7 fp=0xc4220eaf48 sp=0xc4220eae28
github.schq.secious.com/UltraViolet/Winston/lfdb/index.BatchDB.ReadN.func1(0xc420e85ea0, 0xe798a0, 0xc420e85ea0)
	/home/vrecan/go/src/github.schq.secious.com/UltraViolet/Winston/lfdb/index/batchdb.go:144 +0x4a3 fp=0xc4220eb298 sp=0xc4220eaf48
github.schq.secious.com/UltraViolet/Winston/vendor/github.com/boltdb/bolt.(*DB).View(0xc4224323c0, 0xc4220eb378, 0x0, 0x0)
	/home/vrecan/go/src/github.schq.secious.com/UltraViolet/Winston/vendor/github.com/boltdb/bolt/db.go:626 +0xe2 fp=0xc4220eb2f0 sp=0xc4220eb298
github.schq.secious.com/UltraViolet/Winston/lfdb/index.BatchDB.ReadN(0xc422193810, 0x43, 0xc4224323c0, 0x7f78c01f63e2, 0xc, 0xc, 0x2f9b9, 0x1388, 0x1496a3a07fd64200, 0x149fd90987184200, ...)
	/home/vrecan/go/src/github.schq.secious.com/UltraViolet/Winston/lfdb/index/batchdb.go:192 +0x1f8 fp=0xc4220eb3d0 sp=0xc4220eb2f0
github.schq.secious.com/UltraViolet/Winston/lfdb/index.BatchDB.Query(0xc422193810, 0x43, 0xc4224323c0, 0xc423ca6e40, 0x0, 0xc428d016a0, 0x12, 0xc42a5a61e0, 0x43, 0x43)
	/home/vrecan/go/src/github.schq.secious.com/UltraViolet/Winston/lfdb/index/batchdb.go:79 +0x2cf fp=0xc4220eb578 sp=0xc4220eb3d0
github.schq.secious.com/UltraViolet/Winston/lfdb/index.(*BatchDB).Query(0xc422ab21e0, 0xc423ca6e40, 0x0, 0xc428d016a0, 0x12, 0xc42a5a61e0, 0x1, 0x1)
	<autogenerated>:2 +0xcb fp=0xc4220eb5e8 sp=0xc4220eb578
github.schq.secious.com/UltraViolet/Winston/lfdb.Repo.QueryPartition(0xc42051f7d0, 0x5, 0x1, 0xc42051f7d6, 0xa, 0xc42051f7f0, 0x1, 0x1, 0x700000020, 0x0, ...)
	/home/vrecan/go/src/github.schq.secious.com/UltraViolet/Winston/lfdb/repo.go:300 +0x2a5 fp=0xc4220eb6e0 sp=0xc4220eb5e8
github.schq.secious.com/UltraViolet/Winston/server.Winston.queryIndexedPartition(0xc420244a54, 0x7, 0x2d, 0xc42017bc00, 0x1, 0x1, 0xc420243309, 0x2a, 0x1389, 0xc8, ...)
	/home/vrecan/go/src/github.schq.secious.com/UltraViolet/Winston/server/server.go:636 +0x575 fp=0xc4220eb868 sp=0xc4220eb6e0
github.schq.secious.com/UltraViolet/Winston/server.Winston.XQueryPartition(0xc420244a54, 0x7, 0x2d, 0xc42017bc00, 0x1, 0x1, 0xc420243309, 0x2a, 0x1389, 0xc8, ...)
	/home/vrecan/go/src/github.schq.secious.com/UltraViolet/Winston/server/server.go:573 +0xb5 fp=0xc4220eb9b0 sp=0xc4220eb868
github.schq.secious.com/UltraViolet/Winston/server.(*Winston).XQueryPartition(0xc4201023c0, 0xc428d01640, 0x11df220, 0xc426597570, 0x0, 0x7b6ed4)
	<autogenerated>:23 +0xe7 fp=0xc4220ebae0 sp=0xc4220eb9b0
github.schq.secious.com/UltraViolet/Winston/pb._V1_XQueryPartition_Handler(0xdded40, 0xc4201023c0, 0x11de860, 0xc423bf8f00, 0xc4257ced70, 0xc42a28db00)
	/home/vrecan/go/src/github.schq.secious.com/UltraViolet/Winston/pb/v1.pb.go:790 +0x177 fp=0xc4220ebb60 sp=0xc4220ebae0
github.schq.secious.com/UltraViolet/Winston/vendor/google.golang.org/grpc.(*Server).processStreamingRPC(0xc4200d1ba0, 0x11df3a0, 0xc4247ebb20, 0xc42a28db00, 0xc420248570, 0x11fef80, 0xc42a5a6180, 0x0, 0x0)
	/home/vrecan/go/src/github.schq.secious.com/UltraViolet/Winston/vendor/google.golang.org/grpc/server.go:819 +0xe44 fp=0xc4220ebd08 sp=0xc4220ebb60
github.schq.secious.com/UltraViolet/Winston/vendor/google.golang.org/grpc.(*Server).handleStream(0xc4200d1ba0, 0x11df3a0, 0xc4247ebb20, 0xc42a28db00, 0xc42a5a6180)
	/home/vrecan/go/src/github.schq.secious.com/UltraViolet/Winston/vendor/google.golang.org/grpc/server.go:909 +0x170e fp=0xc4220ebf30 sp=0xc4220ebd08
github.schq.secious.com/UltraViolet/Winston/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc426597480, 0xc4200d1ba0, 0x11df3a0, 0xc4247ebb20, 0xc42a28db00)
	/home/vrecan/go/src/github.schq.secious.com/UltraViolet/Winston/vendor/google.golang.org/grpc/server.go:478 +0xb9 fp=0xc4220ebf68 sp=0xc4220ebf30
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2086 +0x1 fp=0xc4220ebf70 sp=0xc4220ebf68
created by github.schq.secious.com/UltraViolet/Winston/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
	/home/vrecan/go/src/github.schq.secious.com/UltraViolet/Winston/vendor/google.golang.org/grpc/server.go:479 +0xbb

goroutine 1 [semacquire, 7 minutes]:
sync.runtime_Semacquire(0xc42017bb9c)
	/usr/local/go/src/runtime/sema.go:47 +0x30
sync.(*WaitGroup).Wait(0xc42017bb90)
	/usr/local/go/src/sync/waitgroup.go:131 +0xbf
github.schq.secious.com/UltraViolet/Winston/vendor/github.com/vrecan/death.(*Death).WaitForDeath(0xc420248060, 0xc42005baa0, 0x2, 0x2)
	/home/vrecan/go/src/github.schq.secious.com/UltraViolet/Winston/vendor/github.com/vrecan/death/death.go:66 +0x68
main.main()
	/home/vrecan/go/src/github.schq.secious.com/UltraViolet/Winston/winston.go:39 +0x683

goroutine 17 [syscall, 7 minutes, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2086 +0x1
```

**Comment by vrecan** [comment]
switching from Batch() to Update() seems to fix it. I have the reads and writes happening in different go routines... Many writers many readers.

**Comment by vrecan** [comment]
never mind spoke too soon.. Just seems a lot less likely that we will see it.

**Comment by vrecan** [comment]
Ok I found out what was causing this. I was using the key outside of the transaction without copying it.
