### ISSUE TITLE
unexpected fault address error when creating a bucket

### ISSUE THREAD

**Issue by meirwah** [boltdb/bolt#661]
```
unexpected fault address 0xc423420000
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x1 addr=0xc423420000 pc=0x610ef6]

goroutine 4587 [running]:
runtime.throw(0x9f1417, 0x5)
	/usr/local/go/src/runtime/panic.go:566 +0x95 fp=0xc4228d1908 sp=0xc4228d18e8
runtime.sigpanic()
	/usr/local/go/src/runtime/sigpanic_unix.go:27 +0x288 fp=0xc4228d1960 sp=0xc4228d1908
github.com/demisto/server/vendor/github.com/boltdb/bolt.(*node).write(0xc4200fe930, 0xc42341fff0)
	/home/ubuntu/.go_workspace/src/github.com/demisto/server/vendor/github.com/boltdb/bolt/node.go:205 +0x86 fp=0xc4228d1aa0 sp=0xc4228d1960
github.com/demisto/server/vendor/github.com/boltdb/bolt.(*Bucket).write(0xc4228d1bb8, 0xc4200fe930, 0x10, 0x0)
	/home/ubuntu/.go_workspace/src/github.com/demisto/server/vendor/github.com/boltdb/bolt/bucket.go:598 +0xb1 fp=0xc4228d1b00 sp=0xc4228d1aa0
github.com/demisto/server/vendor/github.com/boltdb/bolt.(*Bucket).CreateBucket(0xc4207d1380, 0xc421e5b1f0, 0xa, 0x10, 0x9f62a8, 0xa, 0x10)
	/home/ubuntu/.go_workspace/src/github.com/demisto/server/vendor/github.com/boltdb/bolt/bucket.go:181 +0x2bf fp=0xc4228d1c00 sp=0xc4228d1b00
github.com/demisto/server/vendor/github.com/boltdb/bolt.(*Bucket).CreateBucketIfNotExists(0xc4207d1380, 0xc421e5b1f0, 0xa, 0x10, 0xa, 0x10, 0xc4228d1ce0)
	/home/ubuntu/.go_workspace/src/github.com/demisto/server/vendor/github.com/boltdb/bolt/bucket.go:199 +0x4d fp=0xc4228d1c60 sp=0xc4228d1c00
github.com/demisto/server/repo/complexRepo.(*DS).CreateNestedBucket.func1(0xc4233ad420, 0xa6ab08, 0xc4233ad420)
	/home/ubuntu/.go_workspace/src/github.com/demisto/server/repo/complexRepo/store.go:266 +0xd9 fp=0xc4228d1ce0 sp=0xc4228d1c60
github.com/demisto/server/vendor/github.com/boltdb/bolt.(*DB).Update(0xc4220fc780, 0xc4228d1d50, 0x0, 0x0)
	/home/ubuntu/.go_workspace/src/github.com/demisto/server/vendor/github.com/boltdb/bolt/db.go:595 +0xb5 fp=0xc4228d1d30 sp=0xc4228d1ce0
github.com/demisto/server/repo/complexRepo.(*DS).CreateNestedBucket(0xc420f03a20, 0x9f3db0, 0x7, 0x9f62a8, 0xa, 0xcbcca0, 0xc420122230)
```

Happens when a while.. not consistent... any ideas?

bolt revision: c351931701d7d4aa58e41cb735a68400a4e88b29

Any idea?

**Comment by smarterclayton** [comment]
We hit this on an etcd cluster on EC2 on RHEL 7.3 using tmpfs for the disk.  I think we've only seen this once or twice in the last six months - it's not common for us.
